### ISSUE TITLE
axios error

### ISSUE THREAD

**Issue by reiserbc** [7aklhz/strade#2]
I got everything setup but I'm receiving an "Axios error" message. I t hen plugged in my okta info in the gulp.jsfile but I'm not able to get it to load. Are you able to help? 

Thanks 
<img width="1911" alt="axioserrorPNG" src="https://user-images.githubusercontent.com/80236094/139167841-85a134dc-dbec-447a-bfbc-817c886bfae8.PNG">

**Comment by 7aklhz** [comment]
First of call, can you confirm that you also have added your Financial Modeling API credentials ("FMP_API") ? Can you also send me a screenshot of your navigators console logs ?
